### ISSUE TITLE
Please provide install instuctions

### ISSUE THREAD

**Issue by HungryNomad** [7h3rAm/svachal#1]
I really love this project and would like to start using it with my reports as well. I'm having difficulty setting it up form a new Kali install. First there are some requirements such as PIP markdown2, utils, and sparklines. But then in your utils.py you try to import sparkline not sparklines. So I modified that line. After that I'm getting file not found for machines.json. 

If you have time can you please help with a streamlined install. Thank you for your work.

**Comment by Rozakiin** [comment]
Been having the same issues, got a bit further, you need 7h3rAm/machinescli also need to have an environmental variable $HTB_API_KEY set you can find yours on www.hackthebox.eu settings (the old version).

**Comment by kleo** [comment]
You can follow the setup guide I made https://github.com/7h3rAm/svachal/pull/2/files and https://github.com/7h3rAm/machinescli/pull/1/files

**Comment by 7h3rAm** [comment]
Thanks for your patience @HungryNomad, @Rozakiin and @kleo since it took me months to follow up. Thanks to @kleo for documenting install steps and submitting a pull request that is now merged.
